[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"

[env]
ESP_HAL_CONFIG_PLACE_SPI_MASTER_DRIVER_IN_RAM = "true"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-Z", "stack-protector=all",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
